### ISSUE TITLE
What procedures do we need for adding or modifying Pythia datasets?

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/pythia-datasets#20]
We should enumerate our procedures for how to add new datasets to this repository (or elsewhere).  In particular, related to infrastructure, we should take a close look at whether these procedures can be automated or made "push button" in any way.

**Comment by leouieda** [comment]
Not sure if it helps, but we've been experimenting with this in Fatiando here: https://github.com/fatiando/data (with data guidelines here https://github.com/fatiando/data/blob/main/CONTRIBUTING.md)

The types of data we use often need to be heavily edited and standardized since there isn't really a widely used format. So we have the `data` repository for curating and processing. The distribution is then handled by a different package that pulls from the curated data: https://www.fatiando.org/ensaio

**Comment by kmpaul** [comment]
Thanks, @leouieda!  Nice to see you here in Project Pythia!  😄  This is good information.  Thanks for sharing it.

**Comment by dcamron** [comment]
As part of triaging today, we revisited this. It was determined that our actions over the past two years have led in the direction of `pythia-datasets` not being _intended_ for public use and instead just as a tool to serve data specifically in Foundations. We instead advocate for Cookbook contributors to rely on publicly available and accessible datasets or very small per-cookbook data subsets as needed.

It's not been an issue, but it might be worth codifying this sentiment in the README.
